debug: true
assets-path: <replace-me>
sql-host: <replace-me>
sql-port: <replace-me>
sql-password: <replace-me>
http-host: localhost
http-mode: release
http-port: 8080
database-driver: <replace-me>
database-dsn: <replace-me>
