debug: true
assets-path: /home/ye/iChat/assets
sql-host: 127.0.0.1
sql-port: 3307
sql-password:
http-host: localhost
http-mode: release
http-port: 8080
database-driver: mysql
database-dsn: zhengye:csye3631@tcp(127.0.0.1:3307)/discovery?parseTime=true